AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetAllRecipes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getAllRecipes
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: s3://menu-manager-api/menu-manager-api-1549202100.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipes
            Method: get
  GetRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.getRecipe
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: s3://menu-manager-api/menu-manager-api-1549202100.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipes/{recipeId}
            Method: get
  AddRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.addRecipe
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: s3://menu-manager-api/menu-manager-api-1549202100.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipes
            Method: put
  UpdateRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.updateRecipe
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: s3://menu-manager-api/menu-manager-api-1549202100.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipes/{recipeId}
            Method: post
  RemoveRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.deleteRecipe
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: s3://menu-manager-api/menu-manager-api-1549202100.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipes/{recipeId}
            Method: delete
  RecipeTable:
      Type: AWS::Serverless::SimpleTable
