AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-recipe.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipe/{recipeId}
            Method: get
  AddRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add-recipe.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipe
            Method: put
  UpdateRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-recipe.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipe/{recipeId}
            Method: post
  RemoveRecipe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: remove-recipe.handler
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref RecipeTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /recipe/{recipeId}
            Method: delete
  RecipeTable:
      Type: AWS::Serverless::SimpleTable
